// Serkr - An automated theorem prover. Copyright (C) 2015-2016 Mikko Aarnos.
//
// Serkr is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Serkr is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Serkr. If not, see <http://www.gnu.org/licenses/>.
//

//! Contains the parser for the TPTP format.

/// Autogenerated code, don't care about any warnings.
#[allow(missing_docs)]
#[allow(dead_code)]
#[cfg_attr(rustfmt, rustfmt_skip)]
#[cfg_attr(feature="clippy", allow(clippy))]
#[cfg_attr(feature="clippy", allow(clippy_pedantic))]
mod parser_grammar;

/// Contains a function for parsing a formula in the TPTP format to the abstract syntax tree.
#[cfg_attr(rustfmt, rustfmt_skip)]
#[cfg_attr(feature="clippy", allow(result_unwrap_used))]
pub mod parser;

/// The abstract syntax tree the parser constructs.
pub mod ast;
