[package]
name = "serkr"
version = "0.1.0"
authors = ["Mikko Aarnos <mikko.aarnos@gmail.com>"]

[dependencies.time]
time = "*"

[dependencies.peg]
git = "https://github.com/kevinmehall/rust-peg"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"
optional = true

[features]
default = []
dev = ["clippy"]