[package]
name = "serkr"
version = "0.1.0"
authors = ["Mikko Aarnos <mikko.aarnos@gmail.com>"]

build = "build.rs" 

[build-dependencies]
lalrpop = "0.7.0"

[dependencies.lalrpop-util]
lalrpop-util = "0.7.0"

[dependencies.time]
time = "*"

[dependencies.clippy]
clippy = "*"
optional = true

[features]
default = []
dev = ["clippy"]