[package]
name = "serkr"
version = "0.1.0"
authors = ["Mikko Aarnos <mikko.aarnos@gmail.com>"]

build = "build.rs" 

[build-dependencies.lalrpop]
git = "https://github.com/nikomatsakis/lalrpop.git"

[dependencies.lalrpop-util]
git = "https://github.com/nikomatsakis/lalrpop.git"

[dependencies.time]
time = "*"

[dependencies.clippy]
clippy = "*"
optional = true

[features]
dev = ["clippy"]